kotlin.code.style=official
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx3g
pluginVersion=9.1
exposedVersion=0.61.0
hopliteVersion=2.9.0
korlibsVersion=6.0.0-beta4
ktorVersion=3.2.0
skikoVersion=0.9.41
luceneVersion=10.2.2
xmlutilVersion=0.91.1
serializationVersion=1.9.0
h2Version=2.3.232
mariadbVersion=3.5.3
ksoupVersion=0.2.6
opencc4jVersion=1.13.1
mockkVersion=1.14.3
coroutinesVersion=1.10.2