package xyz.xszq.bot.audio.voice

import korlibs.io.file.VfsFile

/**
 * 日文假名转换
 */
class KanaHandler(
    val tokens: Map<String, VfsFile>
) {
    /**
     * 解析单个日语假名转为拼音
     *
     * @param token 日文 token
     * @return 转换结果
     */
    fun clean(token: Token.Raw.Japanese): List<Token> {
        val result = mutableListOf<Token>()

        val found = table.firstOrNull {
            token.text.indexOf(it.first) >= 0
        } ?: run {
            return emptyList()
        }

        val (matched, filenames) = found
        val index = token.text.indexOf(matched)

        val left = token.text.substring(0, index).trim()
        if (left.isNotEmpty())
            result.add(Token.Raw.Japanese(left))

        filenames.forEach { filename ->
            tokens[filename] ?.let {
                result.add(Token.Final.Char(it))
            }
        }

        val right = token.text.substring(index + matched.length).trim()
        if (right.isNotEmpty())
            result.add(Token.Raw.Japanese(right))

        return result
    }
    /**
     * 将日文假名文本转为汉语拼音
     *
     * @param text 日文文本
     * @return 转换结果
     */
    fun parse(text: String): List<Token.Final> {
        var result = mutableListOf<Token>(Token.Raw.Japanese(text))
        var counter = 0
        while (result.any { it is Token.Raw } && counter < 120) {
            val now = mutableListOf<Token>()
            result.forEach { token ->
                if (token is Token.Final)
                    now.add(token)
                else if (token is Token.Raw.Japanese)
                    now.addAll(clean(token))
            }
            result = now
            counter += 1
        }
        return result.filterIsInstance<Token.Final>()
    }

    /**
     * 日语假名与拼音发音对照表
     */
    private val table: Array<Pair<String, Array<String>>> = arrayOf(
        "きゃ" to arrayOf("ke", "ya"),
        "キャ" to arrayOf("ke", "ya"),
        "きゅ" to arrayOf("ke", "yu"),
        "キュ" to arrayOf("ke", "yu"),
        "きょ" to arrayOf("ke", "you"),
        "キョ" to arrayOf("ke", "you"),
        "ぎゃ" to arrayOf("ge", "ya"),
        "ギャ" to arrayOf("ge", "ya"),
        "ぎゅ" to arrayOf("ge", "yu"),
        "ギュ" to arrayOf("ge", "yu"),
        "ぎょ" to arrayOf("ge", "you"),
        "ギョ" to arrayOf("ge", "you"),
        "しゃ" to arrayOf("xia"),
        "シャ" to arrayOf("xia"),
        "しゅ" to arrayOf("xu"),
        "シュ" to arrayOf("xu"),
        "しょ" to arrayOf("xiu"),
        "ショ" to arrayOf("xiu"),
        "ちゃ" to arrayOf("qi", "ya"),
        "チャ" to arrayOf("qi", "ya"),
        "ちゅ" to arrayOf("qu"),
        "チュ" to arrayOf("qu"),
        "ちょ" to arrayOf("qiu"),
        "チョ" to arrayOf("qiu"),
        "じゃ" to arrayOf("jia"),
        "ぢゃ" to arrayOf("jia"),
        "ジャ" to arrayOf("jia"),
        "ヂャ" to arrayOf("jia"),
        "じゅ" to arrayOf("ji", "yu"),
        "ぢゅ" to arrayOf("ji", "yu"),
        "ジュ" to arrayOf("ji", "yu"),
        "ヂュ" to arrayOf("ji", "yu"),
        "じょ" to arrayOf("jiu"),
        "ぢょ" to arrayOf("jiu"),
        "ジョ" to arrayOf("jiu"),
        "ヂョ" to arrayOf("jiu"),
        "にゃ" to arrayOf("ni", "ya"),
        "ニャ" to arrayOf("ni", "ya"),
        "にゅ" to arrayOf("nv"),
        "ニュ" to arrayOf("nv"),
        "にょ" to arrayOf("niu"),
        "ニョ" to arrayOf("niu"),
        "ひゃ" to arrayOf("he", "ya"),
        "ヒャ" to arrayOf("he", "ya"),
        "ひゅ" to arrayOf("he", "yu"),
        "ヒュ" to arrayOf("he", "yu"),
        "ひょ" to arrayOf("he", "you"),
        "ヒョ" to arrayOf("he", "you"),
        "びゃ" to arrayOf("bi", "ya"),
        "ビャ" to arrayOf("bi", "ya"),
        "びゅ" to arrayOf("bi", "yu"),
        "ビュ" to arrayOf("bi", "yu"),
        "びょ" to arrayOf("bi", "you"),
        "ビョ" to arrayOf("bi", "you"),
        "ぴゃ" to arrayOf("pi", "ya"),
        "ピャ" to arrayOf("pi", "ya"),
        "ぴゅ" to arrayOf("pi", "yu"),
        "ピュ" to arrayOf("pi", "yu"),
        "ぴょ" to arrayOf("pi", "you"),
        "ピョ" to arrayOf("pi", "you"),
        "みゃ" to arrayOf("mi", "ya"),
        "ミャ" to arrayOf("mi", "ya"),
        "みゅ" to arrayOf("miu"),
        "ミュ" to arrayOf("miu"),
        "みょ" to arrayOf("mi", "you"),
        "ミョ" to arrayOf("mi", "you"),
        "りゃ" to arrayOf("li", "ya"),
        "リャ" to arrayOf("li", "ya"),
        "りゅ" to arrayOf("li", "yu"),
        "リュ" to arrayOf("li", "yu"),
        "りょ" to arrayOf("liu"),
        "リョ" to arrayOf("liu"),
        "あん" to arrayOf("an"),
        "アン" to arrayOf("an"),
        "いん" to arrayOf("yin"),
        "イン" to arrayOf("yin"),
        "ゐん" to arrayOf("yin"),
        "うん" to arrayOf("wen"),
        "ウン" to arrayOf("wen"),
        "かん" to arrayOf("kan"),
        "カン" to arrayOf("kan"),
        "くん" to arrayOf("kun"),
        "クン" to arrayOf("kun"),
        "こん" to arrayOf("kong"),
        "コン" to arrayOf("kong"),
        "さん" to arrayOf("san"),
        "サン" to arrayOf("san"),
        "しん" to arrayOf("xin"),
        "シン" to arrayOf("xin"),
        "すん" to arrayOf("sen"),
        "スン" to arrayOf("sen"),
        "そん" to arrayOf("song"),
        "ソン" to arrayOf("song"),
        "たん" to arrayOf("tan"),
        "タン" to arrayOf("tan"),
        "ちん" to arrayOf("qin"),
        "チン" to arrayOf("qin"),
        "とん" to arrayOf("tong"),
        "トン" to arrayOf("tong"),
        "なん" to arrayOf("nan"),
        "ナン" to arrayOf("nan"),
        "にん" to arrayOf("ning"),
        "ニン" to arrayOf("ning"),
        "のん" to arrayOf("nong"),
        "ノン" to arrayOf("nong"),
        "はん" to arrayOf("han"),
        "ハン" to arrayOf("han"),
        "ふん" to arrayOf("hun"),
        "フン" to arrayOf("hun"),
        "ほん" to arrayOf("hong"),
        "ホン" to arrayOf("hong"),
        "まん" to arrayOf("man"),
        "マン" to arrayOf("man"),
        "みん" to arrayOf("min"),
        "ミン" to arrayOf("min"),
        "もん" to arrayOf("meng"),
        "モン" to arrayOf("meng"),
        "やん" to arrayOf("yang"),
        "ヤン" to arrayOf("yang"),
        "よん" to arrayOf("yong"),
        "ヨン" to arrayOf("yong"),
        "らん" to arrayOf("lan"),
        "ラン" to arrayOf("lan"),
        "りん" to arrayOf("lin"),
        "リン" to arrayOf("lin"),
        "るん" to arrayOf("lun"),
        "ルン" to arrayOf("lun"),
        "ろん" to arrayOf("long"),
        "ロン" to arrayOf("long"),
        "わん" to arrayOf("wan"),
        "ワン" to arrayOf("wan"),
        "がん" to arrayOf("gan"),
        "ガン" to arrayOf("gan"),
        "ぐん" to arrayOf("gun"),
        "グン" to arrayOf("gun"),
        "ごん" to arrayOf("gong"),
        "ゴン" to arrayOf("gong"),
        "ざん" to arrayOf("zan"),
        "ザン" to arrayOf("zan"),
        "じん" to arrayOf("jin"),
        "ぢん" to arrayOf("jin"),
        "ジン" to arrayOf("jin"),
        "ヂン" to arrayOf("jin"),
        "ぞん" to arrayOf("zong"),
        "ゾン" to arrayOf("zong"),
        "だん" to arrayOf("dan"),
        "ダン" to arrayOf("dan"),
        "どん" to arrayOf("dong"),
        "ドン" to arrayOf("dong"),
        "ばん" to arrayOf("ban"),
        "バン" to arrayOf("ban"),
        "びん" to arrayOf("bin"),
        "ビン" to arrayOf("bin"),
        "ぱん" to arrayOf("pan"),
        "パン" to arrayOf("pan"),
        "ぴん" to arrayOf("pin"),
        "ピン" to arrayOf("pin"),
        "あ" to arrayOf("a"),
        "ア" to arrayOf("a"),
        "ぁ" to arrayOf("a"),
        "ァ" to arrayOf("a"),
        "い" to arrayOf("yi"),
        "イ" to arrayOf("yi"),
        "ぃ" to arrayOf("yi"),
        "ィ" to arrayOf("yi"),
        "ゐ" to arrayOf("yi"),
        "う" to arrayOf("wu"),
        "ウ" to arrayOf("wu"),
        "ぅ" to arrayOf("wu"),
        "ゥ" to arrayOf("wu"),
        "え" to arrayOf("ei"),
        "エ" to arrayOf("ei"),
        "ぇ" to arrayOf("ei"),
        "ェ" to arrayOf("ei"),
        "ゑ" to arrayOf("ei"),
        "お" to arrayOf("ou"),
        "オ" to arrayOf("ou"),
        "ぉ" to arrayOf("ou"),
        "ォ" to arrayOf("ou"),
        "を" to arrayOf("ou"),
        "か" to arrayOf("ka"),
        "カ" to arrayOf("ka"),
        "き" to arrayOf("ke", "yi"),
        "キ" to arrayOf("ke", "yi"),
        "く" to arrayOf("ku"),
        "ク" to arrayOf("ku"),
        "け" to arrayOf("ke", "ei"),
        "ケ" to arrayOf("ke", "ei"),
        "こ" to arrayOf("kou"),
        "コ" to arrayOf("kou"),
        "さ" to arrayOf("sa"),
        "サ" to arrayOf("sa"),
        "し" to arrayOf("xi"),
        "シ" to arrayOf("xi"),
        "す" to arrayOf("si"),
        "ス" to arrayOf("si"),
        "せ" to arrayOf("se", "ei"),
        "セ" to arrayOf("se", "ei"),
        "そ" to arrayOf("sou"),
        "ソ" to arrayOf("sou"),
        "た" to arrayOf("ta"),
        "タ" to arrayOf("ta"),
        "ち" to arrayOf("qi"),
        "チ" to arrayOf("qi"),
        "つ" to arrayOf("ci"),
        "ツ" to arrayOf("ci"),
        "て" to arrayOf("te", "ei"),
        "テ" to arrayOf("te", "ei"),
        "と" to arrayOf("tuo"),
        "ト" to arrayOf("tuo"),
        "な" to arrayOf("na"),
        "ナ" to arrayOf("na"),
        "に" to arrayOf("ni"),
        "ニ" to arrayOf("ni"),
        "ぬ" to arrayOf("nu"),
        "ヌ" to arrayOf("nu"),
        "ね" to arrayOf("nei"),
        "ネ" to arrayOf("nei"),
        "の" to arrayOf("nuo"),
        "ノ" to arrayOf("nuo"),
        "は" to arrayOf("ha"),
        "ハ" to arrayOf("ha"),
        "ひ" to arrayOf("he", "yi"),
        "ヒ" to arrayOf("he", "yi"),
        "ふ" to arrayOf("hu"),
        "フ" to arrayOf("hu"),
        "へ" to arrayOf("hei"),
        "ヘ" to arrayOf("hei"),
        "ほ" to arrayOf("hou"),
        "ホ" to arrayOf("hou"),
        "ま" to arrayOf("ma"),
        "マ" to arrayOf("ma"),
        "み" to arrayOf("mi"),
        "ミ" to arrayOf("mi"),
        "む" to arrayOf("mu"),
        "ム" to arrayOf("mu"),
        "め" to arrayOf("mei"),
        "メ" to arrayOf("mei"),
        "も" to arrayOf("mou"),
        "モ" to arrayOf("mou"),
        "や" to arrayOf("ya"),
        "ヤ" to arrayOf("ya"),
        "ゃ" to arrayOf("ya"),
        "ャ" to arrayOf("ya"),
        "ゆ" to arrayOf("yu"),
        "ユ" to arrayOf("yu"),
        "ゅ" to arrayOf("yu"),
        "ュ" to arrayOf("yu"),
        "よ" to arrayOf("you"),
        "ヨ" to arrayOf("you"),
        "ょ" to arrayOf("you"),
        "ョ" to arrayOf("you"),
        "ら" to arrayOf("la"),
        "ラ" to arrayOf("la"),
        "り" to arrayOf("li"),
        "リ" to arrayOf("li"),
        "る" to arrayOf("lu"),
        "ル" to arrayOf("lu"),
        "れ" to arrayOf("lei"),
        "レ" to arrayOf("lei"),
        "ろ" to arrayOf("lou"),
        "ロ" to arrayOf("lou"),
        "わ" to arrayOf("wa"),
        "ワ" to arrayOf("wa"),
        "が" to arrayOf("ga"),
        "ガ" to arrayOf("ga"),
        "ぎ" to arrayOf("ge", "yi"),
        "ギ" to arrayOf("ge", "yi"),
        "ぐ" to arrayOf("gu"),
        "グ" to arrayOf("gu"),
        "げ" to arrayOf("gei"),
        "ゲ" to arrayOf("gei"),
        "ご" to arrayOf("gou"),
        "ゴ" to arrayOf("gou"),
        "ざ" to arrayOf("za"),
        "ザ" to arrayOf("za"),
        "じ" to arrayOf("ji"),
        "ぢ" to arrayOf("ji"),
        "ジ" to arrayOf("ji"),
        "ヂ" to arrayOf("ji"),
        "ず" to arrayOf("zhi"),
        "づ" to arrayOf("zhi"),
        "ズ" to arrayOf("zhi"),
        "ヅ" to arrayOf("zhi"),
        "ぜ" to arrayOf("zei"),
        "ゼ" to arrayOf("zei"),
        "ぞ" to arrayOf("zou"),
        "ゾ" to arrayOf("zou"),
        "だ" to arrayOf("da"),
        "ダ" to arrayOf("da"),
        "で" to arrayOf("dei"),
        "デ" to arrayOf("dei"),
        "ど" to arrayOf("dou"),
        "ド" to arrayOf("dou"),
        "ば" to arrayOf("ba"),
        "バ" to arrayOf("ba"),
        "び" to arrayOf("bi"),
        "ビ" to arrayOf("bi"),
        "ぶ" to arrayOf("bu"),
        "ブ" to arrayOf("bu"),
        "べ" to arrayOf("bei"),
        "ベ" to arrayOf("bei"),
        "ぼ" to arrayOf("bo"),
        "ボ" to arrayOf("bo"),
        "ぱ" to arrayOf("pa"),
        "パ" to arrayOf("pa"),
        "ぴ" to arrayOf("pi"),
        "ピ" to arrayOf("pi"),
        "ぷ" to arrayOf("pu"),
        "プ" to arrayOf("pu"),
        "ぺ" to arrayOf("pei"),
        "ペ" to arrayOf("pei"),
        "ぽ" to arrayOf("po"),
        "ポ" to arrayOf("po"),
        "ん" to arrayOf("en"),
        "ン" to arrayOf("en"),
    )
}