package xyz.xszq.bot.otto.voice

import korlibs.io.file.VfsFile

class KanaHandler(
    val tokens: Map<String, VfsFile>
) {
    fun clean(token: Token.Raw.Japanese): List<Token> {
        val result = mutableListOf<Token>()

        val found = table.firstOrNull {
            token.text.indexOf(it.first) >= 0
        } ?: run {
            return emptyList()
        }

        val (matched, filenames) = found
        val index = token.text.indexOf(matched)

        val left = token.text.substring(0, index).trim()
        if (left.isNotEmpty())
            result.add(Token.Raw.Japanese(left))

        filenames.forEach { filename ->
            tokens[filename] ?.let {
                result.add(Token.Final.Char(it))
            }
        }

        val right = token.text.substring(index + matched.length).trim()
        if (right.isNotEmpty())
            result.add(Token.Raw.Japanese(right))

        return result
    }
    fun parse(text: String): List<Token.Final> {
        var result = mutableListOf<Token>(Token.Raw.Japanese(text))
        var counter = 0
        while (result.any { it is Token.Raw } && counter < 120) {
            val now = mutableListOf<Token>()
            result.forEach { token ->
                if (token is Token.Final)
                    now.add(token)
                else if (token is Token.Raw.Japanese)
                    now.addAll(clean(token))
            }
            result = now
            counter += 1
        }
        return result.filterIsInstance<Token.Final>()
    }

    private val table: List<Pair<String, List<String>>> = buildList {
        add(Pair("きゃ", listOf("ke", "ya")))
        add(Pair("キャ", listOf("ke", "ya")))
        add(Pair("きゅ", listOf("ke", "yu")))
        add(Pair("キュ", listOf("ke", "yu")))
        add(Pair("きょ", listOf("ke", "you")))
        add(Pair("キョ", listOf("ke", "you")))
        add(Pair("ぎゃ", listOf("ge", "ya")))
        add(Pair("ギャ", listOf("ge", "ya")))
        add(Pair("ぎゅ", listOf("ge", "yu")))
        add(Pair("ギュ", listOf("ge", "yu")))
        add(Pair("ぎょ", listOf("ge", "you")))
        add(Pair("ギョ", listOf("ge", "you")))
        add(Pair("しゃ", listOf("xia")))
        add(Pair("シャ", listOf("xia")))
        add(Pair("しゅ", listOf("xu")))
        add(Pair("シュ", listOf("xu")))
        add(Pair("しょ", listOf("xiu")))
        add(Pair("ショ", listOf("xiu")))
        add(Pair("ちゃ", listOf("qi", "ya")))
        add(Pair("チャ", listOf("qi", "ya")))
        add(Pair("ちゅ", listOf("qu")))
        add(Pair("チュ", listOf("qu")))
        add(Pair("ちょ", listOf("qiu")))
        add(Pair("チョ", listOf("qiu")))
        add(Pair("じゃ", listOf("jia")))
        add(Pair("ぢゃ", listOf("jia")))
        add(Pair("ジャ", listOf("jia")))
        add(Pair("ヂャ", listOf("jia")))
        add(Pair("じゅ", listOf("ji", "yu")))
        add(Pair("ぢゅ", listOf("ji", "yu")))
        add(Pair("ジュ", listOf("ji", "yu")))
        add(Pair("ヂュ", listOf("ji", "yu")))
        add(Pair("じょ", listOf("jiu")))
        add(Pair("ぢょ", listOf("jiu")))
        add(Pair("ジョ", listOf("jiu")))
        add(Pair("ヂョ", listOf("jiu")))
        add(Pair("にゃ", listOf("ni", "ya")))
        add(Pair("ニャ", listOf("ni", "ya")))
        add(Pair("にゅ", listOf("nv")))
        add(Pair("ニュ", listOf("nv")))
        add(Pair("にょ", listOf("niu")))
        add(Pair("ニョ", listOf("niu")))
        add(Pair("ひゃ", listOf("he", "ya")))
        add(Pair("ヒャ", listOf("he", "ya")))
        add(Pair("ひゅ", listOf("he", "yu")))
        add(Pair("ヒュ", listOf("he", "yu")))
        add(Pair("ひょ", listOf("he", "you")))
        add(Pair("ヒョ", listOf("he", "you")))
        add(Pair("びゃ", listOf("bi", "ya")))
        add(Pair("ビャ", listOf("bi", "ya")))
        add(Pair("びゅ", listOf("bi", "yu")))
        add(Pair("ビュ", listOf("bi", "yu")))
        add(Pair("びょ", listOf("bi", "you")))
        add(Pair("ビョ", listOf("bi", "you")))
        add(Pair("ぴゃ", listOf("pi", "ya")))
        add(Pair("ピャ", listOf("pi", "ya")))
        add(Pair("ぴゅ", listOf("pi", "yu")))
        add(Pair("ピュ", listOf("pi", "yu")))
        add(Pair("ぴょ", listOf("pi", "you")))
        add(Pair("ピョ", listOf("pi", "you")))
        add(Pair("みゃ", listOf("mi", "ya")))
        add(Pair("ミャ", listOf("mi", "ya")))
        add(Pair("みゅ", listOf("miu")))
        add(Pair("ミュ", listOf("miu")))
        add(Pair("みょ", listOf("mi", "you")))
        add(Pair("ミョ", listOf("mi", "you")))
        add(Pair("りゃ", listOf("li", "ya")))
        add(Pair("リャ", listOf("li", "ya")))
        add(Pair("りゅ", listOf("li", "yu")))
        add(Pair("リュ", listOf("li", "yu")))
        add(Pair("りょ", listOf("liu")))
        add(Pair("リョ", listOf("liu")))
        add(Pair("あん", listOf("an")))
        add(Pair("アン", listOf("an")))
        add(Pair("いん", listOf("yin")))
        add(Pair("イン", listOf("yin")))
        add(Pair("ゐん", listOf("yin")))
        add(Pair("うん", listOf("wen")))
        add(Pair("ウン", listOf("wen")))
        add(Pair("かん", listOf("kan")))
        add(Pair("カン", listOf("kan")))
        add(Pair("くん", listOf("kun")))
        add(Pair("クン", listOf("kun")))
        add(Pair("こん", listOf("kong")))
        add(Pair("コン", listOf("kong")))
        add(Pair("さん", listOf("san")))
        add(Pair("サン", listOf("san")))
        add(Pair("しん", listOf("xin")))
        add(Pair("シン", listOf("xin")))
        add(Pair("すん", listOf("sen")))
        add(Pair("スン", listOf("sen")))
        add(Pair("そん", listOf("song")))
        add(Pair("ソン", listOf("song")))
        add(Pair("たん", listOf("tan")))
        add(Pair("タン", listOf("tan")))
        add(Pair("ちん", listOf("qin")))
        add(Pair("チン", listOf("qin")))
        add(Pair("とん", listOf("tong")))
        add(Pair("トン", listOf("tong")))
        add(Pair("なん", listOf("nan")))
        add(Pair("ナン", listOf("nan")))
        add(Pair("にん", listOf("ning")))
        add(Pair("ニン", listOf("ning")))
        add(Pair("のん", listOf("nong")))
        add(Pair("ノン", listOf("nong")))
        add(Pair("はん", listOf("han")))
        add(Pair("ハン", listOf("han")))
        add(Pair("ふん", listOf("hun")))
        add(Pair("フン", listOf("hun")))
        add(Pair("ほん", listOf("hong")))
        add(Pair("ホン", listOf("hong")))
        add(Pair("まん", listOf("man")))
        add(Pair("マン", listOf("man")))
        add(Pair("みん", listOf("min")))
        add(Pair("ミン", listOf("min")))
        add(Pair("もん", listOf("meng")))
        add(Pair("モン", listOf("meng")))
        add(Pair("やん", listOf("yang")))
        add(Pair("ヤン", listOf("yang")))
        add(Pair("よん", listOf("yong")))
        add(Pair("ヨン", listOf("yong")))
        add(Pair("らん", listOf("lan")))
        add(Pair("ラン", listOf("lan")))
        add(Pair("りん", listOf("lin")))
        add(Pair("リン", listOf("lin")))
        add(Pair("るん", listOf("lun")))
        add(Pair("ルン", listOf("lun")))
        add(Pair("ろん", listOf("long")))
        add(Pair("ロン", listOf("long")))
        add(Pair("わん", listOf("wan")))
        add(Pair("ワン", listOf("wan")))
        add(Pair("がん", listOf("gan")))
        add(Pair("ガン", listOf("gan")))
        add(Pair("ぐん", listOf("gun")))
        add(Pair("グン", listOf("gun")))
        add(Pair("ごん", listOf("gong")))
        add(Pair("ゴン", listOf("gong")))
        add(Pair("ざん", listOf("zan")))
        add(Pair("ザン", listOf("zan")))
        add(Pair("じん", listOf("jin")))
        add(Pair("ぢん", listOf("jin")))
        add(Pair("ジン", listOf("jin")))
        add(Pair("ヂン", listOf("jin")))
        add(Pair("ぞん", listOf("zong")))
        add(Pair("ゾン", listOf("zong")))
        add(Pair("だん", listOf("dan")))
        add(Pair("ダン", listOf("dan")))
        add(Pair("どん", listOf("dong")))
        add(Pair("ドン", listOf("dong")))
        add(Pair("ばん", listOf("ban")))
        add(Pair("バン", listOf("ban")))
        add(Pair("びん", listOf("bin")))
        add(Pair("ビン", listOf("bin")))
        add(Pair("ぱん", listOf("pan")))
        add(Pair("パン", listOf("pan")))
        add(Pair("ぴん", listOf("pin")))
        add(Pair("ピン", listOf("pin")))
        add(Pair("あ", listOf("a")))
        add(Pair("ア", listOf("a")))
        add(Pair("ぁ", listOf("a")))
        add(Pair("ァ", listOf("a")))
        add(Pair("い", listOf("yi")))
        add(Pair("イ", listOf("yi")))
        add(Pair("ぃ", listOf("yi")))
        add(Pair("ィ", listOf("yi")))
        add(Pair("ゐ", listOf("yi")))
        add(Pair("う", listOf("wu")))
        add(Pair("ウ", listOf("wu")))
        add(Pair("ぅ", listOf("wu")))
        add(Pair("ゥ", listOf("wu")))
        add(Pair("え", listOf("ei")))
        add(Pair("エ", listOf("ei")))
        add(Pair("ぇ", listOf("ei")))
        add(Pair("ェ", listOf("ei")))
        add(Pair("ゑ", listOf("ei")))
        add(Pair("お", listOf("ou")))
        add(Pair("オ", listOf("ou")))
        add(Pair("ぉ", listOf("ou")))
        add(Pair("ォ", listOf("ou")))
        add(Pair("を", listOf("ou")))
        add(Pair("か", listOf("ka")))
        add(Pair("カ", listOf("ka")))
        add(Pair("き", listOf("ke", "yi")))
        add(Pair("キ", listOf("ke", "yi")))
        add(Pair("く", listOf("ku")))
        add(Pair("ク", listOf("ku")))
        add(Pair("け", listOf("ke", "ei")))
        add(Pair("ケ", listOf("ke", "ei")))
        add(Pair("こ", listOf("kou")))
        add(Pair("コ", listOf("kou")))
        add(Pair("さ", listOf("sa")))
        add(Pair("サ", listOf("sa")))
        add(Pair("し", listOf("xi")))
        add(Pair("シ", listOf("xi")))
        add(Pair("す", listOf("si")))
        add(Pair("ス", listOf("si")))
        add(Pair("せ", listOf("se", "ei")))
        add(Pair("セ", listOf("se", "ei")))
        add(Pair("そ", listOf("sou")))
        add(Pair("ソ", listOf("sou")))
        add(Pair("た", listOf("ta")))
        add(Pair("タ", listOf("ta")))
        add(Pair("ち", listOf("qi")))
        add(Pair("チ", listOf("qi")))
        add(Pair("つ", listOf("ci")))
        add(Pair("ツ", listOf("ci")))
        add(Pair("て", listOf("te", "ei")))
        add(Pair("テ", listOf("te", "ei")))
        add(Pair("と", listOf("tuo")))
        add(Pair("ト", listOf("tuo")))
        add(Pair("な", listOf("na")))
        add(Pair("ナ", listOf("na")))
        add(Pair("に", listOf("ni")))
        add(Pair("ニ", listOf("ni")))
        add(Pair("ぬ", listOf("nu")))
        add(Pair("ヌ", listOf("nu")))
        add(Pair("ね", listOf("nei")))
        add(Pair("ネ", listOf("nei")))
        add(Pair("の", listOf("nuo")))
        add(Pair("ノ", listOf("nuo")))
        add(Pair("は", listOf("ha")))
        add(Pair("ハ", listOf("ha")))
        add(Pair("ひ", listOf("he", "yi")))
        add(Pair("ヒ", listOf("he", "yi")))
        add(Pair("ふ", listOf("hu")))
        add(Pair("フ", listOf("hu")))
        add(Pair("へ", listOf("hei")))
        add(Pair("ヘ", listOf("hei")))
        add(Pair("ほ", listOf("hou")))
        add(Pair("ホ", listOf("hou")))
        add(Pair("ま", listOf("ma")))
        add(Pair("マ", listOf("ma")))
        add(Pair("み", listOf("mi")))
        add(Pair("ミ", listOf("mi")))
        add(Pair("む", listOf("mu")))
        add(Pair("ム", listOf("mu")))
        add(Pair("め", listOf("mei")))
        add(Pair("メ", listOf("mei")))
        add(Pair("も", listOf("mou")))
        add(Pair("モ", listOf("mou")))
        add(Pair("や", listOf("ya")))
        add(Pair("ヤ", listOf("ya")))
        add(Pair("ゃ", listOf("ya")))
        add(Pair("ャ", listOf("ya")))
        add(Pair("ゆ", listOf("yu")))
        add(Pair("ユ", listOf("yu")))
        add(Pair("ゅ", listOf("yu")))
        add(Pair("ュ", listOf("yu")))
        add(Pair("よ", listOf("you")))
        add(Pair("ヨ", listOf("you")))
        add(Pair("ょ", listOf("you")))
        add(Pair("ョ", listOf("you")))
        add(Pair("ら", listOf("la")))
        add(Pair("ラ", listOf("la")))
        add(Pair("り", listOf("li")))
        add(Pair("リ", listOf("li")))
        add(Pair("る", listOf("lu")))
        add(Pair("ル", listOf("lu")))
        add(Pair("れ", listOf("lei")))
        add(Pair("レ", listOf("lei")))
        add(Pair("ろ", listOf("lou")))
        add(Pair("ロ", listOf("lou")))
        add(Pair("わ", listOf("wa")))
        add(Pair("ワ", listOf("wa")))
        add(Pair("が", listOf("ga")))
        add(Pair("ガ", listOf("ga")))
        add(Pair("ぎ", listOf("ge", "yi")))
        add(Pair("ギ", listOf("ge", "yi")))
        add(Pair("ぐ", listOf("gu")))
        add(Pair("グ", listOf("gu")))
        add(Pair("げ", listOf("gei")))
        add(Pair("ゲ", listOf("gei")))
        add(Pair("ご", listOf("gou")))
        add(Pair("ゴ", listOf("gou")))
        add(Pair("ざ", listOf("za")))
        add(Pair("ザ", listOf("za")))
        add(Pair("じ", listOf("ji")))
        add(Pair("ぢ", listOf("ji")))
        add(Pair("ジ", listOf("ji")))
        add(Pair("ヂ", listOf("ji")))
        add(Pair("ず", listOf("zhi")))
        add(Pair("づ", listOf("zhi")))
        add(Pair("ズ", listOf("zhi")))
        add(Pair("ヅ", listOf("zhi")))
        add(Pair("ぜ", listOf("zei")))
        add(Pair("ゼ", listOf("zei")))
        add(Pair("ぞ", listOf("zou")))
        add(Pair("ゾ", listOf("zou")))
        add(Pair("だ", listOf("da")))
        add(Pair("ダ", listOf("da")))
        add(Pair("で", listOf("dei")))
        add(Pair("デ", listOf("dei")))
        add(Pair("ど", listOf("dou")))
        add(Pair("ド", listOf("dou")))
        add(Pair("ば", listOf("ba")))
        add(Pair("バ", listOf("ba")))
        add(Pair("び", listOf("bi")))
        add(Pair("ビ", listOf("bi")))
        add(Pair("ぶ", listOf("bu")))
        add(Pair("ブ", listOf("bu")))
        add(Pair("べ", listOf("bei")))
        add(Pair("ベ", listOf("bei")))
        add(Pair("ぼ", listOf("bo")))
        add(Pair("ボ", listOf("bo")))
        add(Pair("ぱ", listOf("pa")))
        add(Pair("パ", listOf("pa")))
        add(Pair("ぴ", listOf("pi")))
        add(Pair("ピ", listOf("pi")))
        add(Pair("ぷ", listOf("pu")))
        add(Pair("プ", listOf("pu")))
        add(Pair("ぺ", listOf("pei")))
        add(Pair("ペ", listOf("pei")))
        add(Pair("ぽ", listOf("po")))
        add(Pair("ポ", listOf("po")))
        add(Pair("ん", listOf("en")))
        add(Pair("ン", listOf("en")))
    }
}