name: Build
on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/build.yml'
    - '.gitignore'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build 
        run: ./gradlew shadowJar
        
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: OtomadBot
          path: build/libs/OtomadBot-*.jar
